version: '3.1'
services:
  
  web:
    build: .
    # depends_on:
    #   - db
    ports:
      - "80:8069"
    volumes:
#      - ./odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./conf:/etc/odoo
 #     - ./entrypoint.sh:/entrypoint.sh


